In [7]:

from commonroad.common.file_reader import CommonRoadFileReader

scenario_path = "scenarios/test_interstate/DEU_test_safe_distance.xml"
# Open scenario. Note, that the lanelet_assignment parameter has to be True!
scenario,_  = CommonRoadFileReader(scenario_path).open(lanelet_assignment=True)

/home/luis/anaconda3/envs/commonroad-py37/lib/python3.7/site-packages/commonroad_io-2021.1-py3.7.egg/commonroad/scenario/scenario.py:333: UserWarning: Not a valid scenario ID: DEU_test_safe_distance
  warnings.warn('Not a valid scenario ID: ' + benchmark_id)

In [8]:
from crmonitor.common.world_state import WorldState

# Create a world state object with ego (the vehicle for which we evaluate)
world = WorldState.create_from_scenario(scenario, ego_obs_id=1003)

In [9]:
from crmonitor.evaluation.evaluation import RuleSetEvaluator

# Create a rule set evaluator with defaults, to evaluate all available rules
evaluator = RuleSetEvaluator.create_from_config()

ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1

In [10]:
# Evaluate the world state object
rule_robustness, predicate_robustness = evaluator.evaluate_incremental(world)

ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1
ANTLR runtime and generated code versions disagree: 4.8!=4.5.1

In [11]:
# The robustness for the full rule
rule_robustness

     time_step rule_name  robustness other_ids
0            0      R_G1    0.047250   (1006,)
1            0      R_G2    0.190476   (1004,)
2            0      R_G3   -0.112032        ()
3            1      R_G1    0.047250   (1006,)
4            1      R_G2    0.190476   (1004,)
..         ...       ...         ...       ...
148         49      R_G2    0.190476   (1004,)
149         49      R_G3    0.187200        ()
150         50      R_G1   -0.037460   (1004,)
151         50      R_G2    0.190476   (1004,)
152         50      R_G3    0.187200        ()

[153 rows x 4 columns]

In [12]:
# The robustness values for each predicate
predicate_robustness

     time_step rule_name                        full_name  robustness
0            0      R_G1            in_same_lane__a0_a1_i   -0.047250
1            0      R_G1             in_front_of__a0_a1_i    0.112460
2            0      R_G1                  cut_in__a1_a0_i   -0.047250
3            0      R_G1  keeps_safe_distance_prec__a0_a1   -0.077302
4            0      R_G2  keeps_safe_distance_prec__a0_a1    0.097698
..         ...       ...                              ...         ...
607         50      R_G2            brakes_abruptly__a0_i   -0.190476
608         50      R_G3       keeps_type_speed_limit__a0    1.000000
609         50      R_G3        keeps_fov_speed_limit__a0    0.288000
610         50      R_G3      keeps_brake_speed_limit__a0    0.187200
611         50      R_G3       keeps_lane_speed_limit__a0    1.000000

[612 rows x 4 columns]